package org.globalmentorship.portal.localization

data class AppStrings(
    // App & Nav
    val appTitle: String,
    val dashboard: String,
    val mentorshipProgram: String,
    val calendar: String,
    val messages: String,
    val notifications: String,
    val settings: String,
    val logout: String,
    val offlineBanner: String,
    val retry: String,

    // Dashboard
    val welcomeBack: String,
    val pauseNotice: String,
    val myMentor: String,
    val myStudent: String,
    val programProgress: String,
    val sessionsCompleted: String,
    val upcomingSessions: String,
    val goToSession: String,
    val recentMessages: String,
    val recentNotifications: String,
    val viewAll: String,
    val noRecentMessages: String,
    val requestHelp: String,

    // Program
    val gmiMentorship: String,
    val nextSession: String,
    val programInstructionTitle: String,
    val programInstructions: String,
    val programIntegrityWarning: String,
    val review: String,
    val current: String,
    val locked: String,
    val completed: String,
    val sessionObjectives: String,
    val downloadableMaterials: String,
    val markSessionComplete: String,
    val markCompleteConfirmTitle: String,
    val markCompleteConfirmMessage: String,
    val confirm: String,
    val cancel: String,

    // Calendar
    val mutualAvailabilityTitle: String,
    val calendarInstructions: String,
    val fullCalendarInstructions: String,
    val addAvailability: String,
    val timezoneRequiredTitle: String,
    val timezoneRequiredMessage: String,
    val configureTimezone: String,
    val legendMentor: String,
    val legendStudent: String,
    val legendSuggested: String,
    val legendConfirmed: String,
    val suggestedMeetingTimes: String,
    val noSuggestedTimes: String,
    val acceptMeeting: String,
    val declineMeeting: String,
    val slotSelectionTitle: String,

    // Notifications
    val unreadNotificationsCount: String,
    val filterAll: String,
    val filterUnread: String,
    val filterRead: String,
    val markAllRead: String,
    val replyToGmi: String,
    val noNotifications: String,

    // Messages
    val tabInbox: String,
    val tabArchived: String,
    val tabDeleted: String,
    val searchConversations: String,
    val emptyConversations: String,
    val newConversation: String,
    val recipient: String,
    val subject: String,
    val subjectCharLimit: String,
    val messageContent: String,
    val messageCharLimit: String,
    val createConversation: String,
    val reply: String,
    val typeMessagePlaceholder: String,
    val send: String,

    // Settings
    val accountDetailsTitle: String,
    val manageAccountSubtitle: String,
    val tabGeneral: String,
    val tabNotifications: String,
    val tabMentorshipHistory: String,
    val tabResume: String,
    val roleLabel: String,
    val createdDate: String,
    val updatedDate: String,
    val profilePhotoGuidance: String,
    val uploadPhoto: String,
    val firstName: String,
    val lastName: String,
    val email: String,
    val timezone: String,
    val timezoneExplainer: String,
    val saveChanges: String,
    val notificationsDefaultGuidance: String,
    val inPortalChannel: String,
    val emailChannel: String,
    val pushChannel: String,
    val uploadResume: String,
    val resourceTypeFile: String,
    val resourceTypeLink: String,
    val documentName: String,
    val externalUrl: String,
    val selectFile: String,
    val uploadedResumes: String,
    val delete: String,
    val languageSwitcher: String,
    val switchRoleDemo: String
) {
    companion object {
        val english = AppStrings(
            appTitle = "GMI Mentorship Portal",
            dashboard = "Dashboard",
            mentorshipProgram = "Program",
            calendar = "Calendar",
            messages = "Messages",
            notifications = "Notifications",
            settings = "Settings",
            logout = "Log Out",
            offlineBanner = "You are currently offline. Changes will sync once reconnected.",
            retry = "Retry",

            welcomeBack = "Welcome back, %s",
            pauseNotice = "If you need to pause your mentorship for more than 2 weeks, please notify us at info@globalmentorship.org.",
            myMentor = "My Mentor",
            myStudent = "My Student(s)",
            programProgress = "Program Progress",
            sessionsCompleted = "%d of 10 sessions completed",
            upcomingSessions = "Upcoming Sessions",
            goToSession = "Go to Session",
            recentMessages = "Recent Messages",
            recentNotifications = "Recent Notifications",
            viewAll = "View all",
            noRecentMessages = "No recent messages",
            requestHelp = "Request Help",

            gmiMentorship = "GMI Mentorship",
            nextSession = "Next: Session %d",
            programInstructionTitle = "Program Progression Guidelines",
            programInstructions = "Sessions must be completed in order. Each completed session unlocks the next milestone, additional career materials, and ultimately the Student Certificate.",
            programIntegrityWarning = "Important: Falsely marking a session complete without meeting your mentor may result in the mentorship being closed. Contact info@globalmentorship.org for assistance.",
            review = "Review",
            current = "Current",
            locked = "Locked",
            completed = "Completed",
            sessionObjectives = "Session Objectives",
            downloadableMaterials = "Materials & Worksheets",
            markSessionComplete = "Mark session complete",
            markCompleteConfirmTitle = "Confirm Session Completion",
            markCompleteConfirmMessage = "Are you sure you want to mark this session as complete? Your partner will be notified, and the next session will unlock. Falsely marking completion violates program guidelines.",
            confirm = "Confirm",
            cancel = "Cancel",

            mutualAvailabilityTitle = "Mutual-Availability Scheduler",
            calendarInstructions = "Tap a date and select the time slots you are available to meet. Your partner compares against their calendar and selects a time. You will receive a notification once confirmed.",
            fullCalendarInstructions = "Full Calendar Instructions",
            addAvailability = "Add Availability",
            timezoneRequiredTitle = "Timezone Configuration Required",
            timezoneRequiredMessage = "All meeting times are calculated in your local timezone. You must set your timezone before viewing or scheduling meetings.",
            configureTimezone = "Set Timezone in Settings",
            legendMentor = "Mentor's Availability",
            legendStudent = "Student's Availability",
            legendSuggested = "Suggested Meeting Time",
            legendConfirmed = "Confirmed Meeting Time",
            suggestedMeetingTimes = "Suggested Meeting Times",
            noSuggestedTimes = "No suggested meeting times.",
            acceptMeeting = "Confirm",
            declineMeeting = "Decline",
            slotSelectionTitle = "Select Available Time Slot",

            unreadNotificationsCount = "%d unread notifications",
            filterAll = "All",
            filterUnread = "Unread (%d)",
            filterRead = "Read",
            markAllRead = "Mark All as Read",
            replyToGmi = "Reply →",
            noNotifications = "No notifications found.",

            tabInbox = "Inbox",
            tabArchived = "Archived",
            tabDeleted = "Deleted",
            searchConversations = "Search conversations...",
            emptyConversations = "No conversations yet — Start a new conversation to get started.",
            newConversation = "New Conversation",
            recipient = "Recipient",
            subject = "Subject",
            subjectCharLimit = "%d/200",
            messageContent = "Message",
            messageCharLimit = "%d/10,000",
            createConversation = "Create Conversation",
            reply = "Reply",
            typeMessagePlaceholder = "Write a message...",
            send = "Send",

            accountDetailsTitle = "Account Details",
            manageAccountSubtitle = "Manage your account information and preferences",
            tabGeneral = "General",
            tabNotifications = "Notifications",
            tabMentorshipHistory = "History",
            tabResume = "Resume",
            roleLabel = "Role",
            createdDate = "Created date",
            updatedDate = "Updated date",
            profilePhotoGuidance = "A square image is recommended and will be center-cropped to a circle. Max 500KB. Formats: JPEG, PNG, GIF, WebP.",
            uploadPhoto = "Upload Photo",
            firstName = "First Name",
            lastName = "Last Name",
            email = "Email",
            timezone = "Timezone",
            timezoneExplainer = "Used to show meeting times correctly. Required before the calendar can be used.",
            saveChanges = "Save Changes",
            notificationsDefaultGuidance = "All options are on by default. Uncheck any to turn off notifications for that event.",
            inPortalChannel = "In-portal notifications",
            emailChannel = "Email notifications",
            pushChannel = "Push notifications",
            uploadResume = "Upload Resume",
            resourceTypeFile = "File Upload",
            resourceTypeLink = "External Link",
            documentName = "Name",
            externalUrl = "External URL",
            selectFile = "Choose File (PDF, DOC, DOCX up to 10MB)",
            uploadedResumes = "Uploaded Resumes",
            delete = "Delete",
            languageSwitcher = "Language",
            switchRoleDemo = "Switch Role View (Student ↔ Mentor)"
        )

        val spanish = english.copy(
            dashboard = "Panel",
            mentorshipProgram = "Programa",
            calendar = "Calendario",
            messages = "Mensajes",
            notifications = "Notificaciones",
            settings = "Ajustes",
            logout = "Cerrar sesión",
            welcomeBack = "Bienvenido de nuevo, %s",
            myMentor = "Mi Mentor",
            myStudent = "Mi Estudiante",
            programProgress = "Progreso del programa",
            sessionsCompleted = "%d de 10 sesiones completadas",
            upcomingSessions = "Próximas sesiones",
            goToSession = "Ir a la sesión",
            recentMessages = "Mensajes recientes",
            recentNotifications = "Notificaciones recientes",
            viewAll = "Ver todo",
            noRecentMessages = "No hay mensajes recientes",
            gmiMentorship = "Mentoría GMI",
            nextSession = "Siguiente: Sesión %d",
            review = "Revisar",
            current = "Actual",
            locked = "Bloqueada",
            completed = "Completada",
            markSessionComplete = "Marcar sesión como completada",
            mutualAvailabilityTitle = "Disponibilidad Mutua",
            addAvailability = "Añadir Disponibilidad",
            suggestedMeetingTimes = "Reuniones Sugeridas",
            noSuggestedTimes = "No hay reuniones sugeridas.",
            unreadNotificationsCount = "%d notificaciones no leídas",
            markAllRead = "Marcar todo como leído",
            replyToGmi = "Responder →",
            newConversation = "Nueva conversación",
            createConversation = "Crear conversación",
            saveChanges = "Guardar cambios",
            languageSwitcher = "Idioma",
            switchRoleDemo = "Cambiar rol (Estudiante ↔ Mentor)"
        )

        val french = english.copy(
            dashboard = "Tableau de bord",
            mentorshipProgram = "Programme",
            calendar = "Calendrier",
            messages = "Messages",
            notifications = "Notifications",
            settings = "Paramètres",
            logout = "Se déconnecter",
            welcomeBack = "Bon retour, %s",
            myMentor = "Mon Mentor",
            myStudent = "Mon Étudiant",
            programProgress = "Progression du programme",
            sessionsCompleted = "%d sur 10 sessions terminées",
            upcomingSessions = "Sessions à venir",
            goToSession = "Accéder à la session",
            recentMessages = "Messages récents",
            recentNotifications = "Notifications récentes",
            viewAll = "Voir tout",
            noRecentMessages = "Aucun message récent",
            gmiMentorship = "Mentorat GMI",
            nextSession = "Suivant : Session %d",
            review = "Examiner",
            current = "En cours",
            locked = "Verrouillée",
            completed = "Terminée",
            markSessionComplete = "Marquer la session comme terminée",
            mutualAvailabilityTitle = "Disponibilité Mutuelle",
            addAvailability = "Ajouter une disponibilité",
            suggestedMeetingTimes = "Horaires de réunion suggérés",
            noSuggestedTimes = "Aucune réunion suggérée.",
            unreadNotificationsCount = "%d notifications non lues",
            markAllRead = "Tout marquer comme lu",
            replyToGmi = "Répondre →",
            newConversation = "Nouvelle conversation",
            createConversation = "Créer une conversation",
            saveChanges = "Enregistrer les modifications",
            languageSwitcher = "Langue",
            switchRoleDemo = "Changer de rôle (Étudiant ↔ Mentor)"
        )
    }
}
