name: iosApp
options:
  bundleIdPrefix: org.globalmentorship
  deploymentTarget:
    iOS: "15.0"
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iosApp
    info:
      path: Info.plist
      properties:
        CADisableMinimumFrameDurationOnPhone: true
        UILaunchScreen: {}
        CFBundleDisplayName: GMI Portal
        UIUserInterfaceStyle: Light
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.globalmentorship.portal
      ARCHS: [arm64]
      ONLY_ACTIVE_ARCH: "YES"
      CODE_SIGNING_ALLOWED: "NO"
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGN_IDENTITY: ""
      OTHER_LDFLAGS:
        - -lc++
        - -framework CoreText
        - -framework CoreGraphics
        - -framework Metal
        - -framework MetalKit
        - -framework QuartzCore
        - -framework ComposeApp
      "FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]":
        - $(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework
      "FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]":
        - $(SRCROOT)/../composeApp/build/bin/iosArm64/debugFramework
